[package]
name = "gelf"
version = "0.1.0"
authors = ["hedgar <hedgar2017@gmail.com>"]

[lib]
name = "slog_gelf"

[dependencies]
slog = "2.2.3"
slog-async = "2.3.0"
log = "0.4.2"
chrono = "0.4.4"
hostname = "0.1.5"
serde = "1.0.66"
serde_json = "1.0.22"