[package]
name = "gelf"
version = "0.1.0"
authors = ["hedgar <hedgar2017@gmail.com>"]

[lib]
name = "slog_gelf"

[dependencies]
slog = "2.2.3"
chrono = "0.4.4"
rand = "0.5.2"
serde = "1.0.66"
serde_json = "1.0.22"

[dev-dependencies]
slog-async = "2.3.0"
hostname = "0.1.5"